#!/usr/bin/ruby
# last_touch
require 'date'

targetDir = ARGV[0]
Dir.chdir("#{targetDir}")
allFiles = Dir.glob "**"


allFiles.each do |f|
  date_timeRaw = `git log --pretty=format:"%ad"`
  date_time    = date_timeRaw.split(" ")
  rev_id       = `git log --pretty=format:"%h"`
  author       = `git log --pretty=format:"%an"`
  dateRaw      = date_time[4] + date_time[1] + date_time[2]
  date         = Date.parse(dateRaw)
  time         = date_time[3]
  timeZoneRaw  = date_time[5]
  colons       = ":"
  timeZone     = timeZoneRaw[0..2] + "#{colons}" + timeZoneRaw[3..4]
  t            = "T"
  space        = " "
  openBracket  = "("
  closeBracket = ")"
  outputStr    = "#{date}" + "#{t}" + "#{time}" + "#{timeZone}" + 
                 "#{space}" + "#{f}" + "#{space}" + "#{openBracket}" +
                 "#{author}" + "#{closeBracket}" 
  puts "#{outputStr}"
  
end

if ARGV.count == 0 then
  targetDir = `pwd`
elsif ARGV.count == 1 then
  subDir = ARGV[0].strip
  if (
else 
  puts "Error"






